# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComponentStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configfactory.Component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user component stars',
                'verbose_name': 'user component star',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usercomponentstar',
            unique_together=set([('user', 'component')]),
        ),
    ]
