name: Move Dev Issue to board
on:
  issues:
    types:
      - labeled

jobs:
  move-issue:
    if: github.event.label.name == 'dev-multisig'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: dev-multisig
          column: Requested
          repo-token: ${{ secrets.GITHUB_TOKEN }}
